version: '2'
services:
    uwsgi:
        build: images/spz
        command: uwsgi --ini /home/spz/code/uwsgi.ini
        ports:
            - "127.0.0.1:3031:3031"
        volumes:
            - ./images/spz/spz:/home/spz/code/spz:ro
            - ./images/spz/util:/home/spz/code/util:ro
            - data_static:/home/spz/code/spz/static
            - state_spz:/state
            - tmp_spz:/tmp
        read_only: true
        environment:
            - MAIL_PORT=tcp://mail:25
            - POSTGRES_PORT=tcp://postgres:5432
            - REDIS_PORT=tcp://redis:6379
            - SPZ_CFG_FILE=/home/spz/code/instance/docker.cfg
        links:
            - mail
            - postgres
            - redis
    rqworker:
        build: images/spz
        command: rqworker --url redis://redis:6379/0
        volumes_from:
            - uwsgi
        read_only: true
        environment:
            - MAIL_PORT=tcp://mail:25
            - POSTGRES_PORT=tcp://postgres:5432
            - REDIS_PORT=tcp://redis:6379
            - SPZ_CFG_FILE=/home/spz/code/instance/docker.cfg
        links:
            - mail
            - postgres
            - redis
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes
        ports:
            - "127.0.0.1:26379:6379"
        volumes:
            - data_redis:/data
        read_only: true
    postgres:
        build: images/postgres
        ports:
            - "127.0.0.1:25432:5432"
        volumes:
            - data_postgres:/var/lib/postgres/data
            - run_postgres:/run/postgresql
            - tmp_postgres:/tmp
        read_only: true
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
    mail:
        image: djfarrelly/maildev
        ports:
            - "127.0.0.1:8081:80"
        volumes:
            - tmp_mail:/tmp
        read_only: true
    nginx:
        build: images/nginx
        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"
        volumes:
            - cache_nginx:/var/cache/nginx
            - data_static:/static
            - tmp_nginx:/tmp
        read_only: true
        links:
            - uwsgi
volumes:
    cache_nginx: {}
    data_postgres: {}
    data_redis: {}
    data_static: {}
    run_postgres: {}
    state_spz: {}
    tmp_mail: {}
    tmp_nginx: {}
    tmp_postgres: {}
    tmp_spz: {}
